proto_homepage:
    path:     /
    defaults: { _controller: ProtoBundle:Home:index }

proto_messenger:
    path:     /messenger
    defaults: { _controller: ProtoBundle:Home:messenger }

new_user:
    path:     /new_user
    defaults: { _controller: ProtoBundle:Home:user_creation }
