proto_homepage:
    path:     /
    defaults: { _controller: ProtoBundle:Home:index }

proto_messenger:
    path:     /messenger{id_conv}
    defaults: { _controller: ProtoBundle:Home:messenger }

new_user:
    path:     /new_user
    defaults: { _controller: ProtoBundle:Home:user_creation }
    
push_msg:
    path:     /push_msg{conv_id}{user_id}{message}
    defaults: { _controller: ProtoBundle:Home:push_msg }